In [1]:
!pip install torch

In [2]:
import torch

1) Создайте случайный FloatTensor размера 3x4x5

In [3]:
t = torch.Tensor(3,4,5)

In [4]:
t

tensor([[[4.9593e+28, 4.2320e+21, 8.6276e+00, 4.6317e+27, 4.3065e+21],
         [7.6724e+34, 3.0345e+32, 4.9639e+28, 2.7946e+20, 2.0535e-19],
         [7.2128e+22, 1.4755e+31, 4.2321e+21, 4.4894e+21, 7.2150e+22],
         [3.2483e+33, 1.9690e-19, 6.8589e+22, 1.3340e+31, 1.1708e-19]],

        [[7.2128e+22, 1.4755e+31, 4.2321e+21, 4.4894e+21, 7.2150e+22],
         [6.2618e+22, 4.7428e+30, 1.1096e+27, 2.7518e+12, 7.5338e+28],
         [4.8156e+30, 1.2102e+25, 1.1839e+22, 1.4605e-19, 9.7269e+05],
         [1.2124e+25, 1.8611e+34, 1.6907e-01, 1.7743e+28, 1.1673e-32]],

        [[7.1345e+31, 7.1118e-04, 6.9772e+22, 1.7704e+31, 7.7447e+31],
         [5.3989e+28, 2.8940e+12, 7.5338e+28, 7.1758e+22, 1.4603e-19],
         [1.8888e+31, 1.2712e+31, 1.4602e-19, 2.0704e-19, 3.3738e-12],
         [4.8226e+27, 2.0704e-19, 6.7421e+22, 1.4226e-13, 6.2608e+22]]])

In [5]:
t.type()

'torch.FloatTensor'

2) Выведите его форму (shape)

In [6]:
t.shape

torch.Size([3, 4, 5])

3) Приведите его к форме 6х10 

In [7]:
t = t.reshape(6, 10)

In [8]:
t.shape

torch.Size([6, 10])

4) Создайте случайный IntTensor размера 10

In [9]:
x = torch.randint(1000, size=(10,))
x

tensor([431, 535, 776,  52, 636, 666, 237, 815, 608, 958])

5) Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [13]:
y = torch.mul(t,x)
y

tensor([[2.1374e+31, 2.2641e+24, 6.6950e+03, 2.4085e+29, 2.7389e+24, 5.1098e+37,
         7.1919e+34, 4.0456e+31, 1.6991e+23, 1.9673e-16],
        [3.1087e+25, 7.8937e+33, 3.2841e+24, 2.3345e+23, 4.5888e+25, 2.1634e+36,
         4.6665e-17, 5.5900e+25, 8.1110e+33, 1.1217e-16],
        [3.1087e+25, 7.8937e+33, 3.2841e+24, 2.3345e+23, 4.5888e+25, 4.1704e+25,
         1.1240e+33, 9.0428e+29, 1.6731e+15, 7.2174e+31],
        [2.0755e+33, 6.4748e+27, 9.1874e+24, 7.5947e-18, 6.1863e+08, 8.0743e+27,
         4.4107e+36, 1.3779e+02, 1.0788e+31, 1.1183e-29],
        [3.0750e+34, 3.8048e-01, 5.4143e+25, 9.2060e+32, 4.9256e+34, 3.5956e+31,
         6.8589e+14, 6.1401e+31, 4.3629e+25, 1.3990e-16],
        [8.1406e+33, 6.8009e+33, 1.1331e-16, 1.0766e-17, 2.1458e-09, 3.2119e+30,
         4.9069e-17, 5.4948e+25, 8.6496e-11, 5.9979e+25]])

In [14]:
y.shape

torch.Size([6, 10])

6) Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [23]:
a = torch.Tensor(6,6)
b = torch.Tensor (6,6)

In [25]:
c = a.mm(b)
c

tensor([[3.0874e-06, 7.7183e-07, 1.1077e-05, 6.9845e-10, 7.0049e-04, 1.6351e-09],
        [2.8342e-06, 6.7458e-07, 1.2160e-05, 3.7151e-10, 6.4469e-04, 1.2683e-09],
        [1.3066e-06, 7.9945e-07, 1.2171e-05, 6.9205e-10, 2.9635e-04, 1.6547e-09],
        [3.2276e-06, 7.9983e-07, 1.1637e-05, 7.4857e-10, 7.3269e-04, 1.7043e-09],
        [3.2548e-06, 6.7493e-07, 1.2587e-05, 6.8487e-10, 7.4009e-04, 1.6079e-09],
        [2.6923e-06, 6.8885e-07, 1.2814e-05, 8.0336e-10, 6.1367e-04, 1.6343e-09]])

In [26]:
c.shape

torch.Size([6, 6])

7) Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [36]:
q = torch.Tensor([1, 0.5, 2])

In [37]:
q.requires_grad = True

In [46]:
f = q**3 + q - 75 * q
f

tensor([ -73.0000,  -36.8750, -140.0000], grad_fn=<SubBackward0>)

In [48]:
f.backward(q)

In [50]:
q.grad

tensor([-142.0000,  -73.2500, -248.0000])

8) Создайте единичный тензор размера 5x6

In [29]:
e = torch.ones(5,6)
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

9) Переведите его в формат numpy

In [35]:
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)